# travis
sudo: false
language: python
cache: pip

jobs:
  fast_finish: true
  include:
    - python: 3.6
      name: flake8-nb
      env: TOXENV=flake8-nb
      after_success:
        - echo "done"

    - language: generic
      python: 3.6
      name: docs
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py36 python=3.6 -y
      install:
        - source activate py36
        - conda config --add channels conda-forge
        - conda install -y --name py36 tox pandoc
        - pip freeze
        - pandoc -v
      script: tox -e docs

    - language: generic
      python: 3.6
      name: docs-links
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py36 python=3.6 -y
      install:
        - source activate py36
        - conda config --add channels conda-forge
        - conda install -y --name py36 tox pandoc
        - pip freeze
        - pandoc -v
      script: tox -e docs-links

    - language: python
      python: "3.6"
      name: linux-py36

    - language: python
      sudo: required
      dist: xenial
      python: "3.7"
      name: linux-py37

    - language: generic
      python: 3.6
      name: osx-py36
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py36 python=3.6 -y
      install:
        - source activate py36
        - conda config --add channels conda-forge
        - conda install -y --name py36 tox
        - pip freeze
      script: tox -e py36

    - language: generic
      python: 3.7
      name: osx-py37
      os: osx
      before_install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - conda update conda -y
        - conda create -n py37 python=3.7 -y
      install:
        - source activate py37
        - conda config --add channels conda-forge
        - conda install -y --name py37 tox coveralls
        - pip freeze
      script: tox -e py37
    - stage: deploy
      name: trigger binder build
      if: branch = master AND type != pull_request
      script:
        # Use Binder build API to trigger repo2docker to build image on GKE and OVH Binder Federation clusters
        - bash binder/trigger_binder.sh https://gke.mybinder.org/build/gh/students-teach-students/python-tools-for-students/master
        - bash binder/trigger_binder.sh https://ovh.mybinder.org/build/gh/students-teach-students/python-tools-for-students/master

  allow_failures:
    #  this tests are allowed to fail since they rely external resources
    - name: docs-links

install:
  - python -m pip install -U pip>=8.1.2
  - pip install tox-travis

script: tox
